services:
  mongo:
    image: mongo:6
    container_name: youtube-mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: youtube-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: youtube-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

